<?php





return array(
        'buckets'=>array(
                'incoming'=>'Incoming',
                'dispatcher'=>'Dispatcher',
                'tracker'=>'Tracker'
            ),
        'move_options'=>array(
                'dispatched'=>'Dispatcher',
                'inprogress'=>'Tracker'
            ),

        'node_type'=>array(
            'hub'=>'Hub',
            'warehouse'=>'Warehouse',
            'courier'=>'Courier',
            '3pl'=>'3PL'),

        'default_heads'=>array(
            array('CREATED DATE',array('search'=>true,'sort'=>true, 'style'=>'min-width:90px;','daterange'=>true)),
            //array('STATUS',array('search'=>true,'select'=>Ks::statusoptions() ,'style'=>'min-width:175px;','sort'=>true)),
            array('CURR POSITION',array('search'=>true,'select'=>Prefs::getPosition()->PositionToSelection('NODE_CODE','NAME') ,'sort'=>true)),
            array('LOGISTIC',array('search'=>true,'sort'=>true)),
            array('SERVICE',array('search'=>true,'sort'=>true)),
            array('CONSIG',array('search'=>true,'sort'=>true)),
            array('AWB',array('search'=>true,'sort'=>true)),
            array('CUST ID',array('search'=>true,'sort'=>true)),
            array('ORDER ID',array('search'=>true,'sort'=>true)),
            array('PICK UP DATE',array('search'=>true,'sort'=>true, 'style'=>'min-width:90px;','daterange'=>true)),
            array('FULFILLMENT ID',array('search'=>true,'sort'=>true)),
            array('NUMBER OF PACKAGE',array('search'=>true,'sort'=>true)),
            array('COD VALUE',array('search'=>true,'sort'=>true)),
            array('EMAIL',array('search'=>true,'sort'=>true)),
            array('NAME',array('search'=>true,'sort'=>true)),
            array('ADDR',array('search'=>true,'style'=>'min-width:250px;width:250px !important;','sort'=>true)),
            array('CITY',array('search'=>true,'sort'=>true)),
            array('REGION',array('search'=>true,'sort'=>true)),
            array('ZIP',array('search'=>true,'sort'=>true)),
            array('PHONE',array('search'=>true,'sort'=>true)),
            array('CONTACT',array('search'=>true,'sort'=>true)),
            array('DESC',array('search'=>true,'sort'=>true)),
            array('W/V',array('search'=>true,'sort'=>true)),
            array('INSURANCE',array('search'=>true,'sort'=>true))

        ),


        'default_fields'=>array(
            array('createdDate',array('kind'=>'daterange' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            //array('status',array('kind'=>'text','callback'=>'statusList','query'=>'like','pos'=>'both','show'=>true, 'multi'=>array('status','warehouse_status','pickup_status'), 'multirel'=>'OR'  )),
            array('POSITION',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('LOGISTIC',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_SERVICE',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIG',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('AWB',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_CUST',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('NO_SALES_ORDER',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('PICK_UP_DATE',array('kind'=>'daterange', 'query'=>'like','pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_ORDERID',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('NUMBER_OF_PACKAGE',array('kind'=>'numeric', 'query'=>'like','pos'=>'both','show'=>true)),
            array('COD',array('kind'=>'currency', 'query'=>'like','pos'=>'both','show'=>true)),
            array('EMAIL',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_NAME',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_ADDR',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_CITY',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_REGION',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_ZIP',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_PHONE',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONTACT',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_DESC',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('W_V',array('kind'=>'numeric' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_INST_AMT',array('kind'=>'currency' , 'query'=>'like', 'pos'=>'both','show'=>true))

        ),

        'default_export_heads'=>array(
            array('CREATED DATE',array('search'=>true,'sort'=>true, 'style'=>'min-width:90px;','daterange'=>true)),
            array('STATUS',array('search'=>true,'select'=>Ks::statusoptions() ,'style'=>'min-width:250px;','sort'=>true)),
            array('COURIER STATUS',array('search'=>true,'select'=>Ks::statusoptions() ,'style'=>'min-width:250px;','sort'=>true)),
            array('PICKUP STATUS',array('search'=>true,'select'=>Ks::statusoptions() ,'style'=>'min-width:250px;','sort'=>true)),
            array('3PL STATUS',array('search'=>true,'select'=>Ks::statusoptions() ,'style'=>'min-width:250px;','sort'=>true)),
            array('WAREHOUSE STATUS',array('search'=>true,'select'=>Ks::statusoptions() ,'style'=>'min-width:250px;','sort'=>true)),
            array('CONSIG',array('search'=>true,'sort'=>true)),
            array('ORDER ID',array('search'=>true,'sort'=>true)),
            array('PICK UP DATE',array('search'=>true,'sort'=>true, 'style'=>'min-width:90px;','daterange'=>true)),
            array('FULFILLMENT ID',array('search'=>true,'sort'=>true)),
            array('NUMBER OF PACKAGE',array('search'=>true,'sort'=>true)),
            array('COD VALUE',array('search'=>true,'sort'=>true)),
            array('EMAIL',array('search'=>true,'sort'=>true)),
            array('NAME',array('search'=>true,'sort'=>true)),
            array('ADDR',array('search'=>true,'style'=>'min-width:120px;width:120px !important;','sort'=>true)),
            array('CITY',array('search'=>true,'sort'=>true)),
            array('REGION',array('search'=>true,'sort'=>true)),
            array('ZIP',array('search'=>true,'sort'=>true)),
            array('PHONE',array('search'=>true,'sort'=>true)),
            array('CONTACT',array('search'=>true,'sort'=>true)),
            array('DESC',array('search'=>true,'sort'=>true)),
            array('W/V',array('search'=>true,'sort'=>true)),
            array('AWB',array('search'=>true,'sort'=>true)),
            array('CUST ID',array('search'=>true,'sort'=>true)),
            array('SERVICE',array('search'=>true,'sort'=>true)),
            array('INSURANCE',array('search'=>true,'sort'=>true))

        ),

        'default_export_fields'=>array(
            array('createdDate',array('kind'=>'daterange' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('status',array('kind'=>'text','query'=>'like','pos'=>'both','show'=>true, 'multi'=>array('status','warehouse_status','pickup_status'), 'multirel'=>'OR'  )),
            array('courier_status',array('kind'=>'text','query'=>'like','pos'=>'both','show'=>true, 'multi'=>array('status','warehouse_status','pickup_status'), 'multirel'=>'OR'  )),
            array('pickup_status',array('kind'=>'text','query'=>'like','pos'=>'both','show'=>true, 'multi'=>array('status','warehouse_status','pickup_status'), 'multirel'=>'OR'  )),
            array('3pl_status',array('kind'=>'text','query'=>'like','pos'=>'both','show'=>true, 'multi'=>array('status','warehouse_status','pickup_status'), 'multirel'=>'OR'  )),
            array('warehouse_status',array('kind'=>'text','query'=>'like','pos'=>'both','show'=>true, 'multi'=>array('status','warehouse_status','pickup_status'), 'multirel'=>'OR'  )),
            array('CONSIG',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('NO_SALES_ORDER',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('PICK_UP_DATE',array('kind'=>'daterange', 'query'=>'like','pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_ORDERID',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('NUMBER_OF_PACKAGE',array('kind'=>'numeric', 'query'=>'like','pos'=>'both','show'=>true)),
            array('COD',array('kind'=>'currency', 'query'=>'like','pos'=>'both','show'=>true)),
            array('EMAIL',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_NAME',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_ADDR',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_CITY',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_REGION',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_ZIP',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_PHONE',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONTACT',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_DESC',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('W_V',array('kind'=>'numeric' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('AWB',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_CUST',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_SERVICE',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_INST_AMT',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true))

        ),

        'default_zoning_heads'=>array(
            array('CREATED DATE',array('search'=>true,'sort'=>true, 'style'=>'min-width:90px;','daterange'=>true)),
            array('PICK UP DATE',array('search'=>true,'sort'=>true, 'style'=>'min-width:120px;','daterange'=>true)),
            array('CITY',array('search'=>true,'style'=>'min-width:120px;','sort'=>true)),
            //array('STATUS',array('search'=>true,'select'=>Ks::statusoptions() ,'style'=>'min-width:175px;','sort'=>true)),
            array('CURR POSITION',array('search'=>true,'select'=>Prefs::getPosition()->PositionToSelection('NODE_CODE','NAME') ,'sort'=>true)),
            array('LOGISTIC',array('search'=>true,'sort'=>true)),
            array('SERVICE',array('search'=>true,'sort'=>true)),
            array('CONSIG',array('search'=>true,'sort'=>true)),
            array('AWB',array('search'=>true,'sort'=>true)),
            array('CUST ID',array('search'=>true,'sort'=>true)),
            array('ORDER ID',array('search'=>true,'sort'=>true)),
            array('FULFILLMENT ID',array('search'=>true,'sort'=>true)),
            array('NUMBER OF PACKAGE',array('search'=>true,'sort'=>true)),
            array('COD VALUE',array('search'=>true,'sort'=>true)),
            array('EMAIL',array('search'=>true,'sort'=>true)),
            array('NAME',array('search'=>true,'sort'=>true)),
            array('ADDR',array('search'=>true,'style'=>'min-width:250px;width:250px !important;','sort'=>true)),
            array('CITY',array('search'=>true,'sort'=>true)),
            array('REGION',array('search'=>true,'sort'=>true)),
            array('ZIP',array('search'=>true,'sort'=>true)),
            array('PHONE',array('search'=>true,'sort'=>true)),
            array('CONTACT',array('search'=>true,'sort'=>true)),
            array('DESC',array('search'=>true,'sort'=>true)),
            array('W/V',array('search'=>true,'sort'=>true)),
            array('INSURANCE',array('search'=>true,'sort'=>true))

        ),


        'default_zoning_fields'=>array(
            array('createdDate',array('kind'=>'daterange' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('PICK_UP_DATE',array('kind'=>'daterange', 'query'=>'like','pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_CITY',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            //array('status',array('kind'=>'text','callback'=>'statusList','query'=>'like','pos'=>'both','show'=>true, 'multi'=>array('status','warehouse_status','pickup_status'), 'multirel'=>'OR'  )),
            array('POSITION',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('LOGISTIC',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_SERVICE',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIG',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('AWB',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_CUST',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('NO_SALES_ORDER',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_ORDERID',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('NUMBER_OF_PACKAGE',array('kind'=>'numeric', 'query'=>'like','pos'=>'both','show'=>true)),
            array('COD',array('kind'=>'currency', 'query'=>'like','pos'=>'both','show'=>true)),
            array('EMAIL',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_NAME',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_ADDR',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_CITY',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_REGION',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_ZIP',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_PHONE',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONTACT',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_DESC',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('W_V',array('kind'=>'numeric' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_INST_AMT',array('kind'=>'currency' , 'query'=>'like', 'pos'=>'both','show'=>true))

        ),

        'default_courierassign_heads'=>array(
            array('CREATED DATE',array('search'=>true,'sort'=>true, 'style'=>'min-width:90px;','daterange'=>true)),
            array('PICK UP DATE',array('search'=>true,'sort'=>true, 'style'=>'min-width:120px;','daterange'=>true)),
            array('DEVICE ID',array('search'=>true,'style'=>'min-width:120px;','sort'=>true)),
            //array('STATUS',array('search'=>true,'select'=>Ks::statusoptions() ,'style'=>'min-width:175px;','sort'=>true)),
            array('CURR POSITION',array('search'=>true,'select'=>Prefs::getPosition()->PositionToSelection('NODE_CODE','NAME') ,'sort'=>true)),
            array('LOGISTIC',array('search'=>true,'sort'=>true)),
            array('SERVICE',array('search'=>true,'sort'=>true)),
            array('CONSIG',array('search'=>true,'sort'=>true)),
            array('AWB',array('search'=>true,'sort'=>true)),
            array('CUST ID',array('search'=>true,'sort'=>true)),
            array('ORDER ID',array('search'=>true,'sort'=>true)),
            array('FULFILLMENT ID',array('search'=>true,'sort'=>true)),
            array('NUMBER OF PACKAGE',array('search'=>true,'sort'=>true)),
            array('COD VALUE',array('search'=>true,'sort'=>true)),
            array('EMAIL',array('search'=>true,'sort'=>true)),
            array('NAME',array('search'=>true,'sort'=>true)),
            array('ADDR',array('search'=>true,'style'=>'min-width:250px;width:250px !important;','sort'=>true)),
            array('CITY',array('search'=>true,'sort'=>true)),
            array('REGION',array('search'=>true,'sort'=>true)),
            array('ZIP',array('search'=>true,'sort'=>true)),
            array('PHONE',array('search'=>true,'sort'=>true)),
            array('CONTACT',array('search'=>true,'sort'=>true)),
            array('DESC',array('search'=>true,'sort'=>true)),
            array('W/V',array('search'=>true,'sort'=>true)),
            array('INSURANCE',array('search'=>true,'sort'=>true))

        ),


        'default_courierassign_fields'=>array(
            array('createdDate',array('kind'=>'daterange' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('PICK_UP_DATE',array('kind'=>'daterange', 'query'=>'like','pos'=>'both','show'=>true)),
            array('DEVICE_ID',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            //array('status',array('kind'=>'text','callback'=>'statusList','query'=>'like','pos'=>'both','show'=>true, 'multi'=>array('status','warehouse_status','pickup_status'), 'multirel'=>'OR'  )),
            array('POSITION',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('LOGISTIC',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_SERVICE',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIG',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('AWB',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_CUST',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('NO_SALES_ORDER',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_ORDERID',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('NUMBER_OF_PACKAGE',array('kind'=>'numeric', 'query'=>'like','pos'=>'both','show'=>true)),
            array('COD',array('kind'=>'currency', 'query'=>'like','pos'=>'both','show'=>true)),
            array('EMAIL',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_NAME',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_ADDR',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_CITY',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_REGION',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_ZIP',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_PHONE',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONTACT',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_DESC',array('kind'=>'text' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('W_V',array('kind'=>'numeric' , 'query'=>'like', 'pos'=>'both','show'=>true)),
            array('CONSIGNEE_OLSHOP_INST_AMT',array('kind'=>'currency' , 'query'=>'like', 'pos'=>'both','show'=>true))

        ),

    );